### ISSUE TITLE
Integration does not implement services

### ISSUE THREAD

**Issue by preben529** [dingusdk/haihc-betatest#19]
2 controllers in setup, both on hardware 7.1 and firmware 3.3.44
Integration v.2024.3.1
IHCViewer v.2024.3.1

IHCViewer works fine and can call both IHC-controlers
But from automations or panel-actions i get **Action ihc.set_runtime_value_float not found**

## Debug log

2024-10-13 18:36:00.428 ERROR (MainThread) [homeassistant.components.automation.varme_spejl_gulvvarme_z_points_til_ihc] varme spejl gulvvarme z-points til IHC: Error executing script. Service not found for call_service at pos 1: Action ihc.set_runtime_value_float not found
2024-10-13 18:36:00.442 ERROR (MainThread) [homeassistant.components.automation.check_sth_1_sal_temperatur] check sth 1. sal temperatur: Choose at step 1: choice 2: Error executing script. Service not found for call_service at pos 1: Action ihc.set_runtime_value_bool not found
2024-10-13 18:36:00.443 ERROR (MainThread) [homeassistant.components.automation.check_sth_1_sal_temperatur] check sth 1. sal temperatur: Error executing script. Service not found for choose at pos 1: Action ihc.set_runtime_value_bool not found

**Comment by dingusdk** [comment]
Can you give an example of your action in the automation. Something like:
```yaml
action: ihc.set_runtime_value_float
data:
  ihc_id: 2193940
  value: 1.2 
```
The value should be a float
Can you call it from the "Developer tools|Actions"
Is this related to having 2 controllers?

**Comment by preben529** [comment]
I think the automations are fine and have been working for years 🙂

To me it seems like something goes wrong during HA- system start

It all started when i upgraded to the BETA-ihc-integration

Today i installed 'my image' on another computer, it worked normal for an hour or so, then i rebooted, due to upgrade of HA.

And after that reboot it does not work again 🙁
________________________________
Fra: Jens Østergaard Nielsen ***@***.***>
Sendt: 17. oktober 2024 10:33
Til: dingusdk/haihc-betatest ***@***.***>
Cc: Preben Nørrisgaard ***@***.***>; Author ***@***.***>
Emne: Re: [dingusdk/haihc-betatest] Integration does not implement services (Issue #19)


Can you give an example of your action in the automation. Something like:

action: ihc.set_runtime_value_float
data:
  ihc_id: 2193940
  value: 1.2

The value should be a float
Can you call it from the "Developer tools|Actions"
Is this related to having 2 controllers?

**Comment by preben529** [comment]
When the problem occurs i cant choose the IHC.* actions.... see picture below


[cid:c5548660-dbee-4353-a992-6fbb26e90830]
[cid:dc5cb01a-652e-4003-896e-e4f14c4e3681]


________________________________
Fra: Jens Østergaard Nielsen ***@***.***>
Sendt: 17. oktober 2024 10:33
Til: dingusdk/haihc-betatest ***@***.***>
Cc: Preben Nørrisgaard ***@***.***>; Author ***@***.***>
Emne: Re: [dingusdk/haihc-betatest] Integration does not implement services (Issue #19)


Can you give an example of your action in the automation. Something like:

action: ihc.set_runtime_value_float
data:
  ihc_id: 2193940
  value: 1.2

The value should be a float
Can you call it from the "Developer tools|Actions"
Is this related to having 2 controllers?

**Comment by preben529** [comment]
Can you please advice me to supply you with debug info or what ever..... the problem is VERY persistent now.

**Comment by dingusdk** [comment]
The issue about the "Integration does not implement services" is a "side effect" of the ihc integration not loading. (That is what I assume).
I have lately experienced similar problems when restarting Home Assistant. I get errors in the log that the IHC controller has closed the connection. Can you look in your log and see if you have something similar? Should be the first error you get related to IHC after restart.
I am investigating further - it looks like the problem is timing related, the IHC integration has not changed, so it must be something in HA that cause the controller to misbehave.

**Comment by dingusdk** [comment]
I have made a new version of the: [IHC sdk module](https://github.com/dingusdk/PythonIhcSdk/releases/tag/v2.8.9). This will retry failed requests 3 times. I will need to test a while before releasing it to the IHC integration.
If you want to test it you can edit your IHC integration manifest file, and change ihcsdk to 2.8.9 - you can find the file in your custom_components/ihc folder:

```yaml
{
  "domain": "ihc",
  "name": "IHC controller",
  "documentation": "https://www.home-assistant.io/integrations/ihc",
  "requirements": [
    "defusedxml==0.6.0",
    "ihcsdk==2.8.9"
  ],
  "codeowners": [
    "@dingusdk"
  ],
  "config_flow": true,
  "iot_class": "local_push",
  "version": "2024.11.0"
}
```
Restart HA after the change.

**Comment by preben529** [comment]
I have started using it, but it does not help.

it has been fine during the week (since monday) It seems like troubles started same time as last weekend 🙁

Could be that HA depends on something 'very important' outside my house.




________________________________
Fra: Jens Østergaard Nielsen ***@***.***>
Sendt: 15. november 2024 13:49
Til: dingusdk/haihc-betatest ***@***.***>
Cc: Preben Nørrisgaard ***@***.***>; Author ***@***.***>
Emne: Re: [dingusdk/haihc-betatest] Integration does not implement services (Issue #19)


I have made a new version of the: IHC sdk module<https://github.com/dingusdk/PythonIhcSdk/releases/tag/v2.8.9>. This will retry failed requests 3 times. I will need to test a while before releasing it to the IHC integration.
If you want to test it you can edit your IHC integration manifest file, and change ihcsdk to 2.8.9 - you can find the file in your custom_components/ihc folder:

{
  "domain": "ihc",
  "name": "IHC controller",
  "documentation": "https://www.home-assistant.io/integrations/ihc",
  "requirements": [
    "defusedxml==0.6.0",
    "ihcsdk==2.8.9"
  ],
  "codeowners": [
    ***@***.***"
  ],
  "config_flow": true,
  "iot_class": "local_push",
  "version": "2024.11.0"
}

Restart HA after the change.

**Comment by dingusdk** [comment]
After you have restarted HA and the IHC integration is not starting correctly, look for the first error entry in the log related to the IHC controller, and post it here. (Note the newest entry is in the top, so you should look at the bottom). Any errors you get later may not be relevant, these are because the IHC integration is not started (like service actions not working)

**Comment by preben529** [comment]
These are 1. IHC log entry from the 2 latest restarts, and integration is not working.....

Logger: homeassistant.util.loop
Kilde: util/loop.py:136
Første forekomst: 22.16.21 (1 forekomster)
Senest logget: 22.16.21

Detected blocking call to listdir with args ('/config/custom_components/ihcviewer/frontend',) inside the event loop by custom integration 'ihcviewer' at custom_components/ihcviewer/__init__.py, line 117: dirlist = os.listdir(path) (offender: /config/custom_components/ihcviewer/__init__.py, line 117: dirlist = os.listdir(path)), please report it to the author of the 'ihcviewer' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component result = await task File "/config/custom_components/ihcviewer/__init__.py", line 43, in async_setup register_frontend(hass) File "/config/custom_components/ihcviewer/__init__.py", line 117, in register_frontend dirlist = os.listdir(path)






Logger: homeassistant.util.loop
Kilde: util/loop.py:136
Første forekomst: 22.07.33 (1 forekomster)
Senest logget: 22.07.33

Detected blocking call to listdir with args ('/config/custom_components/ihcviewer/frontend',) inside the event loop by custom integration 'ihcviewer' at custom_components/ihcviewer/__init__.py, line 117: dirlist = os.listdir(path) (offender: /config/custom_components/ihcviewer/__init__.py, line 117: dirlist = os.listdir(path)), please report it to the author of the 'ihcviewer' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component result = await task File "/config/custom_components/ihcviewer/__init__.py", line 43, in async_setup register_frontend(hass) File "/config/custom_components/ihcviewer/__init__.py", line 117, in register_frontend dirlist = os.listdir(path)

________________________________
Fra: Jens Østergaard Nielsen ***@***.***>
Sendt: 16. november 2024 13:46
Til: dingusdk/haihc-betatest ***@***.***>
Cc: Preben Nørrisgaard ***@***.***>; Author ***@***.***>
Emne: Re: [dingusdk/haihc-betatest] Integration does not implement services (Issue #19)


After you have restarted HA and the IHC integration is not starting correctly, look for the first error entry in the log related to the IHC controller, and post it here. (Note the newest entry is in the top, so you should look at the bottom). Any errors you get later may not be relevant, these are because the IHC integration is not started (like service actions not working)

**Comment by preben529** [comment]
And now its running again.... after restoring BU
Maybe it started this time due to Home Assistant Core Update from 2024.11.1 to 2024.11.2
Not saying the core update is bad, but it started the nonworking situation.



________________________________
Fra: Jens Østergaard Nielsen ***@***.***>
Sendt: 16. november 2024 13:46
Til: dingusdk/haihc-betatest ***@***.***>
Cc: Preben Nørrisgaard ***@***.***>; Author ***@***.***>
Emne: Re: [dingusdk/haihc-betatest] Integration does not implement services (Issue #19)


After you have restarted HA and the IHC integration is not starting correctly, look for the first error entry in the log related to the IHC controller, and post it here. (Note the newest entry is in the top, so you should look at the bottom). Any errors you get later may not be relevant, these are because the IHC integration is not started (like service actions not working)

**Comment by collinhenrik** [comment]
Hi,

I'm having similar problem with my 2 controller setup. What we discovered is that the problem only occurs when both controllers are enabled. So if you only enable one controller en restart HA the IHC action are available and can be used. But if you activate also the second controller en restart HA the IHC action dissapear and you get an error. 
Please find hereafter my debug information:

**IHC control - Action ihc.pulse not found with two controllers enabled**

**Description of the problem** 
I’m trying to configure scripts for the IHC control integration for my two home controllers. When I enable only one controller I can use the IHC actions in my scripts such as ihc.pulse but when I enable both controllers (and restart HA) all IHC actions disappear and for the existing script I receive the following errors:

Error running action
Action ihc.pulse not found

Error in describing action: e.services[t] is undefined


**First Home Assistant version with the issue** 
It never worked. Started with HA version 2025.4.1 and now upgrade towards version 2025.4.2 with same issue. But I don't think the HA version has an impact.

**Last working Home Assistant release (if known)** 
It never worked with the versions I installed

**Operating environment** 
I’m currently using Home Assistant Operating System 15.2 (previously version 15.1 with same issue)

**Integration** 
[/integrations/ihc/](https://www.home-assistant.io/integrations/hue/)

**Diagnostics information** 
025-04-16 08:52:28.279 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ihcviewer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-16 08:52:28.280 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration recycle_app which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-16 08:52:28.281 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-16 08:52:28.282 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ihc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-16 08:52:30.980 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /ws/ControllerService
2025-04-16 08:52:31.599 DEBUG (MainThread) [custom_components.ihc.ihcdevice] Adding IHC entity notify event: 997466
2025-04-16 08:52:31.890 DEBUG (MainThread) [custom_components.ihc.ihcdevice] Adding IHC entity notify event: 982106
..............
2025-04-16 08:52:32.023 DEBUG (MainThread) [custom_components.ihc.ihcdevice] Adding IHC entity notify event: 19290
2025-04-16 08:52:44.885 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Service not found for call_service at pos 1: Action ihc.pulse not found
2025-04-16 08:52:44.885 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547853548224] Action ihc.pulse not found


**Additional information** 
With one controller enabled everything works fine. Once a second controller is activated and the HA system is restarted the problem occurs. Deactivating one of the two controllers and restarting the system solves the problem. But I need to able to use both controllers.
Script yaml code:
action: ihc.pulse
metadata: {}
data:
  ihc_id: 986970
  controller_id: "24637"

HA info:
Home Assistant Core - 2025.4.2
Home Assistant Operating System - 15.2

Integration info:
IHC Control version 2024.11.0

Controller info:
GARDY 6.1 by Schneider Electric controllers x 2
Firmware: 2.7.220 

controller ID 1: 24637
controller ID 2: 21004

button ID: 986970 --- Living_986970 --- binary_sensor.living_986970

**Comment by preben529** [comment]
Could this bee of any help ?
I get this in my log , the ip address is matching the second controller which is the one most often beeing non operable from homeassistant. 
 Logger: urllib3.connectionpool
Kilde: /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:323
Første forekomst: 23. maj 2025 kl. 22.50.11 (24 occurrences)
Senest logget: 08.35.17

Connection pool is full, discarding connection: 192.xx.x0.x8. Connection pool size: 10

**Comment by collinhenrik** [comment]
Hi,

Many thanks for your input.
It seems that there is indeed an issue with the urllib3.connectionpool script. See error below:

2025-05-28 15:36:22.162 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /ws/ControllerService

But when a capture the traffic towards both controllers at interface level of the HA host both controllers do respond with a 200 ok. So at network and controller level everything seems ok (see printscreen below)

![Image](https://github.com/user-attachments/assets/f9f8f703-7c3d-4f9b-8ffa-2664f9676d51)

Same output for both when I enable only one and then (separately enabled) they both work fine.
I will perform some further debug and keep you posted

Cheers
